### ISSUE TITLE
Installing dependencies from elm-package.json

### ISSUE THREAD

**Issue by G4BB3R** [sbrink/vscode-elm#22]
It would be great to have an option to install dependencies with F1 + "Elm: install dependencies"
or by pressing Ctrl + F5 on elm-package.json file.

**Comment by stkb** [comment]
This is one of the first things I thought of too when trying out the extension, though then I thought hmm, it's not actually that hard to do ```ctrl+shift+c``` to open up a console and then type ```elm package install```.

I still think it would be nice to have, although sometimes the elm package installer requires extra input and that might be tricky to deal with.

**Comment by G4BB3R** [comment]
Windows is not terminal-friendly. It requires time to open the Windows Powershell.
But on Linux/OSX I agree.

**Comment by stkb** [comment]
I still agree with having the feature but I just want to say I don't agree that it's difficult on Windows, which I use myself.

If you press ```ctrl+shift+c``` within vscode it brings up cmd.exe in the current project root folder, and for this case cmd is perfectly adequate.

I don't use PowerShell either, partly because it's slower to open. I actually use Git Bash, which comes with [Git for Windows](https://git-for-windows.github.io/) and basically gives you Bash on Windows. Then I use the [Open in User-defined Console](https://marketplace.visualstudio.com/items/vilicvane.console) for vscode which lets me remap the "open console" keyboard shortcut to launch git bash instead of cmd.exe.

**Comment by Krzysztof-Cieslak** [comment]
Implemented in `0.5.0`
