### ISSUE TITLE
Repl does not work well for LF new line character

### ISSUE THREAD

**Issue by zerkms** [sbrink/vscode-elm#37]
If you define a simple binding as

```elm
the_answer =
  42
```

it fails with the syntax error.

It works fine with the CRLF though

**Comment by stkb** [comment]
Hi @zerkms, the elm-repl code has had some re-working since the last 0.5.1 release, and for me using the latest code from master, this seems to be working fine (I can't test the 0.5.1 version because on that version the repl doesn't work for me at all).

If you want, you can try downloading the latest version of the extension from here, into your .vscode/extensions folder, and see if that fixes it.

**Comment by zerkms** [comment]
Sure, I will do today and will close/report on the results. Thanks.

**Comment by csmith111** [comment]
Just tested and this seems to work fine for single line and multiline bindings. I am running the elm repl 0.16.0 version.
